#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 160

#define PERMISSIVE_HOLD

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 18

#define SERIAL_NUMBER "Qx0lg/EeWZnG"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 5

#define RGB_MATRIX_STARTUP_SPD 60

